import dotenv from "dotenv";

dotenv.config();

export const {
  APP_PORT,
  APP_MONGODB_URI,
  APP_ACCESS_TOKEN_SECRET,
  APP_ACCESS_TOKEN_EXP,
  APP_REFRESH_TOKEN_SECRET,
  APP_REFRESH_TOKEN_EXP,
  APP_CLOUDINARY_NAME,
  APP_CLOUDINARY_API_KEY,
  APP_CLOUDINARY_SECRET_KEY,
} = process.env;
